Repository deepanshs/mrsimulator, pull requests merged in 2022-03, with the labels that each got.

#112 Memory improvement for single_site_system_generator
  .flake8
  .github/workflows/continuous-integration-pip.yml
  .pre-commit-config.yaml
  docs/conf.py
  src/mrsimulator/method/__init__.py
  src/mrsimulator/methods/stvas.py
  src/mrsimulator/models/tests/test_czjzek_and_extended_czjzek.py
  src/mrsimulator/models/tests/test_model_utils.py
  src/mrsimulator/models/utils.py
  src/mrsimulator/signal_processing/tests/test_apodization.py
  src/mrsimulator/signal_processing/tests/test_baseline.py
  src/mrsimulator/spin_system/site.py
  src/mrsimulator/spin_system/tests/test_site.py
  src/mrsimulator/tests/test_mrsimulator_class.py
  src/mrsimulator/utils/collection.py
  src/mrsimulator/utils/extra.py
  src/mrsimulator/utils/tests/test_extra.py
  src/mrsimulator/utils/tests/test_single_site_sys_gen.py
  tests/2D_spectrum_tests/test_das.py
  tests/2D_spectrum_tests/test_mqmas.py
  tests/python_test_for_c_code/angular_momentum.py
  tests/wigner/matrix/wigner_matrix_test.py
  tests/wigner/wigner_rotation_test.py
Labels: resource management

#130 Add support for defining SpectralDimension for NamedMethod.
  docs/api_py/methods/BlochDecayCTSpectrum.rst
  docs/api_py/methods/BlochDecaySpectrum.rst
  docs/introduction/ethanol_example.rst
  docs/introduction/getting_started.rst
  docs/user_guide/methods_library/bloch_decay.rst
  docs/user_guide/methods_library/bloch_decay_CT.rst
  docs/user_guide/methods_library/mq_vas.rst
  docs/user_guide/methods_library/ssb2d.rst
  docs/user_guide/methods_library/st_vas.rst
  docs/user_guide/simulator/simulator.rst
  examples_source/1D_simulation(crystalline)/plot_0_Wollastonite.py
  examples_source/1D_simulation(crystalline)/plot_1_PotassiumSulfate.py
  examples_source/1D_simulation(crystalline)/plot_2_Coesite.py
  examples_source/1D_simulation(crystalline)/plot_3_quad_csa.py
  examples_source/1D_simulation(crystalline)/plot_6_dipolar_coupled.py
  examples_source/1D_simulation(crystalline)/plot_7_CAS_dipolar_J.py
  examples_source/1D_simulation(macro_amorphous)/plot_3_amorphous_like.py
  examples_source/1D_simulation(macro_amorphous)/plot_4_amorphous_like_quad.py
  examples_source/1D_simulation(macro_amorphous)/plot_5_czjzek_distribution.py
  examples_source/1D_simulation(macro_amorphous)/plot_6_extended_czjzek.py
  examples_source/2D_simulation(crystalline)/plot_0_MQMAS_RbNO3.py
  examples_source/2D_simulation(crystalline)/plot_1_MQMAS_albite.py
  examples_source/2D_simulation(crystalline)/plot_1_STMAS_RbNO3.py
  examples_source/2D_simulation(crystalline)/plot_4_3QMAS_Coesite.py
  examples_source/2D_simulation(crystalline)/plot_6_PASS_itraconazole_drug.py
  examples_source/2D_simulation(crystalline)/plot_7_QSSB_Rb2SO4.py
  examples_source/2D_simulation(macro_amorphous)/plot_0_crystalline_disorder.py
  examples_source/2D_simulation(macro_amorphous)/plot_1_I=2.5.py
  fitting_source/1D_fitting/plot_1_29Si_cuspidine.py
  src/mrsimulator/methods/base.py
  src/mrsimulator/methods/tests/test_MQVAS.py
  src/mrsimulator/methods/tests/test_base.py
  src/mrsimulator/methods/utils.py
  tests/test_orientations_and_triangle_interpolation.py
Labels: enhancement

#126 Documentation for method object.
  docs/api_c/frequency_tensor_components.rst
  docs/api_c/spatial_orientation_tensor_components.rst
  docs/api_c/spin_transition_functions.rst
  docs/api_py/method/event.rst
  docs/api_py/method/query.rst
  docs/conf.py
  docs/index.rst
  docs/theory/components.rst
  docs/user_guide/io/mrsim_IO.rst
  docs/user_guide/method/method_advanced_user.rst
  docs/user_guide/method/query_objects.rst
  docs/user_guide/methods_library/bloch_decay_CT.rst
  docs/user_guide/simulator/simulator.rst
  examples_source/1D_simulation(crystalline)/plot_9_custom_method_Hahnecho.py
  src/mrsimulator/methods/base.py
Labels: documentation
